FROM python:3.12-slim

WORKDIR /src
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY engine/requirements-build.txt /tmp/requirements-build.txt
RUN pip install --no-cache-dir -r /tmp/requirements-build.txt

COPY app /src/app
COPY agent /src/agent
COPY engine /src/engine

RUN python engine/setup.py build_ext --inplace
